on:
  push:
    branches:
      - master

name: ğŸš€ Deploy Laravel Project

jobs:
  deploy:
    name: ğŸ‰ Deploy to Hostinger
    runs-on: ubuntu-latest

    steps:
      - name: ğŸšš Checkout code
        uses: actions/checkout@v4

      - name: ğŸ“¦ Install dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: âš™ï¸ Prepare the application
        run: |
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      - name: ğŸ“‚ Sync files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: www.liqwidcode.site
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          server-dir: /etrabaho.liqwidcode.site/
          exclude: |
            .git*
            storage/*.log
